project_name: stash-box
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
builds:
- id: stash-box-win
  binary: stash-box-win
  ldflags: -extldflags='-static' -s -w
  goos:
    - windows
  goarch:
    - amd64
  env:
    - CC=x86_64-w64-mingw32-gcc 
    - CXX=x86_64-w64-mingw32-g++ 
- id: stash-box-linux
  binary: stash-box-linux
  ldflags: -extldflags='-static' -s -w
  goos:
    - linux
  goarch:
    - amd64
- id: stash-box-osx
  binary: stash-box-osx
  goos:
    - darwin
  goarch:
    - amd64
  env:
    - CC=o64-clang
    - CXX=o64-clang++

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
- format: binary

dockers:
  - image_templates:
    - peroo/stash-box
  ids:
    - stash-box-linux
  dockerfile: docker/ci/x86_64/Dockerfile
