#import "../fragments/PerformerFragment.gql"
#import "../fragments/StudioFragment.gql"
#import "../fragments/ImageFragment.gql"
#import "../fragments/SceneFragment.gql"
#import "../fragments/TagFragment.gql"
#import "../fragments/CommentFragment.gql"
#import "../fragments/URLFragment.gql"
#import "../fragments/FingerprintFragment.gql"
#import "../fragments/OldTagEditDetails.gql"
#import "../fragments/OldSceneEditDetails.gql"
#import "../fragments/OldPerformerEditDetails.gql"
#import "../fragments/OldStudioEditDetails.gql"
#import "../fragments/NewTagEditDetails.gql"
#import "../fragments/NewStudioEditDetails.gql"
#import "../fragments/NewSceneEditDetails.gql"
#import "../fragments/NewPerformerEditDetails.gql"
fragment EditFragment on Edit {
  id
  target_type
  operation
  status
  applied
  created
  updated
  vote_count
  destructive
  comments {
    ...CommentFragment
  }
  votes {
    user {
      id
      name
    }
    date
    vote
  }
  user {
    id
    name
  }
  target {
    ... on Tag {
      ...TagFragment
    }
    ... on Performer {
      ...PerformerFragment
    }
    ... on Studio {
      ...StudioFragment
    }
    ... on Scene {
      ...SceneFragment
    }
  }
  details {
    ... on TagEdit {
      ...NewTagEditDetails
    }
    ... on PerformerEdit {
      ...NewPerformerEditDetails
    }
    ... on StudioEdit {
      ...NewStudioEditDetails
    }
    ... on SceneEdit {
      ...NewSceneEditDetails
    }
  }
  old_details {
    ... on TagEdit {
      ...OldTagEditDetails
    }
    ... on PerformerEdit {
      ...OldPerformerEditDetails
    }
    ... on StudioEdit {
      ...OldStudioEditDetails
    }
    ... on SceneEdit {
      ...OldSceneEditDetails
    }
  }
  merge_sources {
    ... on Tag {
      ...TagFragment
    }
    ... on Performer {
      ...PerformerFragment
    }
    ... on Studio {
      ...StudioFragment
    }
    ... on Scene {
      ...SceneFragment
    }
  }
  options {
    set_modify_aliases
    set_merge_aliases
  }
}
