fragment OldPerformerEditDetails on PerformerEdit {
  name
  disambiguation
  gender
  birthdate
  birthdate_accuracy
  ethnicity
  country
  eye_color
  hair_color
  height
  cup_size
  band_size
  waist_size
  hip_size
  breast_type
  career_start_year
  career_end_year
}
