#import "../fragments/ImageFragment.gql"
#import "../fragments/ScenePerformerFragment.gql"
#import "../fragments/URLFragment.gql"
fragment SceneFragment on Scene {
  id
  release_date
  title
  deleted
  details
  code
  duration
  urls {
    ...URLFragment
  }
  images {
    ...ImageFragment
  }
  studio {
    id
    name
    parent {
      id
      name
    }
  }
  credits {
    as
    performer {
      ...ScenePerformerFragment
    }
    type
  }
  fingerprints {
    hash
    algorithm
    duration
    submissions
    user_submitted
    created
    updated
  }
  tags {
    id
    name
    description
    aliases
  }
}
