#import "./PerformerFragment.gql"
#import "./CreditTypeFragment.gql"
#import "./CreditAttributeFragment.gql"
fragment SceneCreditEditFragment on SceneCreditEdit {
  performer {
    ...PerformerFragment
  }
  credit_type {
    ...CreditTypeFragment
  }
  as
  attributes {
    ...CreditAttributeFragment
  }
}
