#import "../fragments/PerformerFragment.gql"
#import "../fragments/CreditRoleFragment.gql"
#import "../fragments/TagFragment.gql"
query FullPerformer($id: ID!) {
  findPerformer(id: $id) {
    ...PerformerFragment
    studios {
      scene_count
      studio {
        id
        name
        parent {
          id
          name
        }
      }
    }
    credit_roles {
      scene_count
      role {
        ...CreditRoleFragment
      }
      tags {
        scene_count
        tag {
          ...TagFragment
        }
      }
    }
  }
}
