#import "../fragments/PerformerFragment.gql"
#import "../fragments/CreditTypeFragment.gql"
query FullPerformer($id: ID!) {
  findPerformer(id: $id) {
    ...PerformerFragment
    studios {
      scene_count
      studio {
        id
        name
        parent {
          id
          name
        }
      }
    }
    credit_types {
      scene_count
      credit_type {
        ...CreditTypeFragment
      }
    }
  }
}
