#import "../fragments/ImageFragment.gql"
#import "../fragments/SearchPerformerFragment.gql"
#import "../fragments/SearchScene.gql"
#import "../fragments/URLFragment.gql"
query SearchAll($term: String!, $limit: Int = 5) {
    searchPerformer(term: $term, limit: $limit) {
      ...SearchPerformerFragment
    }
    searchScene(term: $term, limit: $limit) {
      ...SearchScene
    }
}
