package main

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/sqlc-dev/plugin-sdk-go/codegen"
	"github.com/sqlc-dev/plugin-sdk-go/plugin"
)

func main() { codegen.Run(generate) }

func generate(_ context.Context, req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	var tables []*plugin.Table
	for _, schema := range req.GetCatalog().GetSchemas() {
		if schema.GetName() == req.GetCatalog().GetDefaultSchema() || schema.GetName() == "public" {
			tables = append(tables, schema.GetTables()...)
		}
	}
	sort.Slice(tables, func(i, j int) bool { return tables[i].GetRel().GetName() < tables[j].GetRel().GetName() })
	var b bytes.Buffer
	b.WriteString("// Code generated by sqlc-gen-querybuilder. DO NOT EDIT.\npackage queryschema\n\nimport (\n\t\"time\"\n\t\"github.com/gofrs/uuid\"\n\n\tqb \"github.com/stashapp/stash-box/pkg/querybuilder\"\n)\n\nvar (\n\t_ = time.Time{}\n\t_ = uuid.Nil\n)\n\n")
	for _, table := range tables {
		if table.GetRel() == nil {
			continue
		}
		goName := exported(table.GetRel().GetName())
		typeName := goName + "Table"
		fmt.Fprintf(&b, "type %s struct {\n\tqb.Table\n\tAllColumns qb.Expression\n", typeName)
		seen := map[string]int{}
		for _, col := range table.GetColumns() {
			n := exported(col.GetName())
			seen[n]++
			if seen[n] > 1 {
				n += fmt.Sprint(seen[n])
			}
			fmt.Fprintf(&b, "\t%s qb.Column[%s]\n", n, goType(col))
		}
		b.WriteString("}\n\n")
		fmt.Fprintf(&b, "func new%s(name string) %s {\n\tt := %s{Table: qb.NewTable(\"%s\")}\n\tt.Table.Alias = name\n\tq := t.Table.Qualifier()\n", goName, typeName, typeName, table.GetRel().GetName())
		seen = map[string]int{}
		for _, col := range table.GetColumns() {
			n := exported(col.GetName())
			seen[n]++
			if seen[n] > 1 {
				n += fmt.Sprint(seen[n])
			}
			fmt.Fprintf(&b, "\tt.%s = qb.NewColumn[%s](q, \"%s\")\n", n, goType(col), col.GetName())
		}
		b.WriteString("\tt.AllColumns = qb.Columns(")
		seen = map[string]int{}
		for i, col := range table.GetColumns() {
			n := exported(col.GetName())
			seen[n]++
			if seen[n] > 1 {
				n += fmt.Sprint(seen[n])
			}
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "t.%s", n)
		}
		b.WriteString(")\n\treturn t\n}\n")
		fmt.Fprintf(&b, "func (t %s) AS(alias string) %s { return new%s(alias) }\nvar %s = new%s(\"\")\n\n", typeName, typeName, goName, goName, goName)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated schema: %w\n%s", err, b.String())
	}
	return &plugin.GenerateResponse{Files: []*plugin.File{{Name: "schema.gen.go", Contents: src}}}, nil
}

func goType(c *plugin.Column) string {
	name := strings.ToLower(c.GetType().GetName())
	var typ string
	switch name {
	case "uuid":
		typ = "uuid.UUID"
	case "bool", "boolean":
		typ = "bool"
	case "int2", "smallint", "int4", "integer", "serial", "serial4":
		typ = "int"
	case "int8", "bigint", "bigserial", "serial8":
		typ = "int64"
	case "float4", "real", "float8", "double precision", "numeric", "decimal":
		typ = "float64"
	case "timestamp", "timestamptz", "timestamp without time zone", "timestamp with time zone":
		typ = "time.Time"
	case "bytea":
		typ = "[]byte"
	default:
		typ = "string"
	}
	if c.GetIsArray() {
		typ = "[]" + typ
	}
	return typ
}
func exported(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' })
	for i, part := range parts {
		switch strings.ToLower(part) {
		case "id":
			parts[i] = "ID"
		case "url":
			parts[i] = "URL"
		case "ip":
			parts[i] = "IP"
		case "api":
			parts[i] = "API"
		default:
			r := []rune(part)
			if len(r) > 0 {
				r[0] = unicode.ToUpper(r[0])
			}
			parts[i] = string(r)
		}
	}
	return strings.Join(parts, "")
}
