// Code generated by sqlc-gen-querybuilder. DO NOT EDIT.
package queryschema

import (
	"github.com/gofrs/uuid"
	"time"

	qb "github.com/stashapp/stash-box/pkg/querybuilder"
)

var (
	_ = time.Time{}
	_ = uuid.Nil
)

type DraftsTable struct {
	qb.Table
	AllColumns qb.Expression
	ID         qb.Column[uuid.UUID]
	UserID     qb.Column[uuid.UUID]
	Type       qb.Column[string]
	Data       qb.Column[string]
	CreatedAt  qb.Column[time.Time]
}

func newDrafts(name string) DraftsTable {
	t := DraftsTable{Table: qb.NewTable("drafts")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.Type = qb.NewColumn[string](q, "type")
	t.Data = qb.NewColumn[string](q, "data")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.AllColumns = qb.Columns(t.ID, t.UserID, t.Type, t.Data, t.CreatedAt)
	return t
}
func (t DraftsTable) AS(alias string) DraftsTable { return newDrafts(alias) }

var Drafts = newDrafts("")

type EditCommentsTable struct {
	qb.Table
	AllColumns qb.Expression
	ID         qb.Column[uuid.UUID]
	EditID     qb.Column[uuid.UUID]
	UserID     qb.Column[uuid.UUID]
	CreatedAt  qb.Column[time.Time]
	Text       qb.Column[string]
	UpdatedAt  qb.Column[time.Time]
	IsHidden   qb.Column[bool]
}

func newEditComments(name string) EditCommentsTable {
	t := EditCommentsTable{Table: qb.NewTable("edit_comments")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.EditID = qb.NewColumn[uuid.UUID](q, "edit_id")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.Text = qb.NewColumn[string](q, "text")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.IsHidden = qb.NewColumn[bool](q, "is_hidden")
	t.AllColumns = qb.Columns(t.ID, t.EditID, t.UserID, t.CreatedAt, t.Text, t.UpdatedAt, t.IsHidden)
	return t
}
func (t EditCommentsTable) AS(alias string) EditCommentsTable { return newEditComments(alias) }

var EditComments = newEditComments("")

type EditVotesTable struct {
	qb.Table
	AllColumns qb.Expression
	EditID     qb.Column[uuid.UUID]
	UserID     qb.Column[uuid.UUID]
	CreatedAt  qb.Column[time.Time]
	Vote       qb.Column[string]
}

func newEditVotes(name string) EditVotesTable {
	t := EditVotesTable{Table: qb.NewTable("edit_votes")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.EditID = qb.NewColumn[uuid.UUID](q, "edit_id")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.Vote = qb.NewColumn[string](q, "vote")
	t.AllColumns = qb.Columns(t.EditID, t.UserID, t.CreatedAt, t.Vote)
	return t
}
func (t EditVotesTable) AS(alias string) EditVotesTable { return newEditVotes(alias) }

var EditVotes = newEditVotes("")

type EditsTable struct {
	qb.Table
	AllColumns  qb.Expression
	ID          qb.Column[uuid.UUID]
	UserID      qb.Column[uuid.UUID]
	Operation   qb.Column[string]
	TargetType  qb.Column[string]
	Data        qb.Column[string]
	Votes       qb.Column[int]
	Status      qb.Column[string]
	Applied     qb.Column[bool]
	CreatedAt   qb.Column[time.Time]
	UpdatedAt   qb.Column[time.Time]
	ClosedAt    qb.Column[time.Time]
	Bot         qb.Column[bool]
	UpdateCount qb.Column[int]
}

func newEdits(name string) EditsTable {
	t := EditsTable{Table: qb.NewTable("edits")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.Operation = qb.NewColumn[string](q, "operation")
	t.TargetType = qb.NewColumn[string](q, "target_type")
	t.Data = qb.NewColumn[string](q, "data")
	t.Votes = qb.NewColumn[int](q, "votes")
	t.Status = qb.NewColumn[string](q, "status")
	t.Applied = qb.NewColumn[bool](q, "applied")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.ClosedAt = qb.NewColumn[time.Time](q, "closed_at")
	t.Bot = qb.NewColumn[bool](q, "bot")
	t.UpdateCount = qb.NewColumn[int](q, "update_count")
	t.AllColumns = qb.Columns(t.ID, t.UserID, t.Operation, t.TargetType, t.Data, t.Votes, t.Status, t.Applied, t.CreatedAt, t.UpdatedAt, t.ClosedAt, t.Bot, t.UpdateCount)
	return t
}
func (t EditsTable) AS(alias string) EditsTable { return newEdits(alias) }

var Edits = newEdits("")

type FingerprintsTable struct {
	qb.Table
	AllColumns qb.Expression
	ID         qb.Column[int]
	Algorithm  qb.Column[string]
	Hash       qb.Column[int64]
}

func newFingerprints(name string) FingerprintsTable {
	t := FingerprintsTable{Table: qb.NewTable("fingerprints")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[int](q, "id")
	t.Algorithm = qb.NewColumn[string](q, "algorithm")
	t.Hash = qb.NewColumn[int64](q, "hash")
	t.AllColumns = qb.Columns(t.ID, t.Algorithm, t.Hash)
	return t
}
func (t FingerprintsTable) AS(alias string) FingerprintsTable { return newFingerprints(alias) }

var Fingerprints = newFingerprints("")

type ImagesTable struct {
	qb.Table
	AllColumns qb.Expression
	ID         qb.Column[uuid.UUID]
	URL        qb.Column[string]
	Width      qb.Column[int]
	Height     qb.Column[int]
	Checksum   qb.Column[string]
}

func newImages(name string) ImagesTable {
	t := ImagesTable{Table: qb.NewTable("images")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.URL = qb.NewColumn[string](q, "url")
	t.Width = qb.NewColumn[int](q, "width")
	t.Height = qb.NewColumn[int](q, "height")
	t.Checksum = qb.NewColumn[string](q, "checksum")
	t.AllColumns = qb.Columns(t.ID, t.URL, t.Width, t.Height, t.Checksum)
	return t
}
func (t ImagesTable) AS(alias string) ImagesTable { return newImages(alias) }

var Images = newImages("")

type InviteKeysTable struct {
	qb.Table
	AllColumns  qb.Expression
	ID          qb.Column[uuid.UUID]
	GeneratedBy qb.Column[uuid.UUID]
	GeneratedAt qb.Column[time.Time]
	Uses        qb.Column[int]
	ExpireTime  qb.Column[time.Time]
}

func newInviteKeys(name string) InviteKeysTable {
	t := InviteKeysTable{Table: qb.NewTable("invite_keys")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.GeneratedBy = qb.NewColumn[uuid.UUID](q, "generated_by")
	t.GeneratedAt = qb.NewColumn[time.Time](q, "generated_at")
	t.Uses = qb.NewColumn[int](q, "uses")
	t.ExpireTime = qb.NewColumn[time.Time](q, "expire_time")
	t.AllColumns = qb.Columns(t.ID, t.GeneratedBy, t.GeneratedAt, t.Uses, t.ExpireTime)
	return t
}
func (t InviteKeysTable) AS(alias string) InviteKeysTable { return newInviteKeys(alias) }

var InviteKeys = newInviteKeys("")

type ModAuditTable struct {
	qb.Table
	AllColumns qb.Expression
	ID         qb.Column[uuid.UUID]
	Action     qb.Column[string]
	UserID     qb.Column[uuid.UUID]
	TargetID   qb.Column[uuid.UUID]
	TargetType qb.Column[string]
	Data       qb.Column[string]
	Reason     qb.Column[string]
	CreatedAt  qb.Column[time.Time]
}

func newModAudit(name string) ModAuditTable {
	t := ModAuditTable{Table: qb.NewTable("mod_audit")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Action = qb.NewColumn[string](q, "action")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.TargetID = qb.NewColumn[uuid.UUID](q, "target_id")
	t.TargetType = qb.NewColumn[string](q, "target_type")
	t.Data = qb.NewColumn[string](q, "data")
	t.Reason = qb.NewColumn[string](q, "reason")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.AllColumns = qb.Columns(t.ID, t.Action, t.UserID, t.TargetID, t.TargetType, t.Data, t.Reason, t.CreatedAt)
	return t
}
func (t ModAuditTable) AS(alias string) ModAuditTable { return newModAudit(alias) }

var ModAudit = newModAudit("")

type NotificationsTable struct {
	qb.Table
	AllColumns qb.Expression
	UserID     qb.Column[uuid.UUID]
	Type       qb.Column[string]
	ID         qb.Column[uuid.UUID]
	CreatedAt  qb.Column[time.Time]
	ReadAt     qb.Column[time.Time]
	Data       qb.Column[string]
}

func newNotifications(name string) NotificationsTable {
	t := NotificationsTable{Table: qb.NewTable("notifications")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.Type = qb.NewColumn[string](q, "type")
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.ReadAt = qb.NewColumn[time.Time](q, "read_at")
	t.Data = qb.NewColumn[string](q, "data")
	t.AllColumns = qb.Columns(t.UserID, t.Type, t.ID, t.CreatedAt, t.ReadAt, t.Data)
	return t
}
func (t NotificationsTable) AS(alias string) NotificationsTable { return newNotifications(alias) }

var Notifications = newNotifications("")

type PerformerAliasesTable struct {
	qb.Table
	AllColumns  qb.Expression
	PerformerID qb.Column[uuid.UUID]
	Alias       qb.Column[string]
}

func newPerformerAliases(name string) PerformerAliasesTable {
	t := PerformerAliasesTable{Table: qb.NewTable("performer_aliases")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.Alias = qb.NewColumn[string](q, "alias")
	t.AllColumns = qb.Columns(t.PerformerID, t.Alias)
	return t
}
func (t PerformerAliasesTable) AS(alias string) PerformerAliasesTable {
	return newPerformerAliases(alias)
}

var PerformerAliases = newPerformerAliases("")

type PerformerEditsTable struct {
	qb.Table
	AllColumns  qb.Expression
	EditID      qb.Column[uuid.UUID]
	PerformerID qb.Column[uuid.UUID]
}

func newPerformerEdits(name string) PerformerEditsTable {
	t := PerformerEditsTable{Table: qb.NewTable("performer_edits")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.EditID = qb.NewColumn[uuid.UUID](q, "edit_id")
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.AllColumns = qb.Columns(t.EditID, t.PerformerID)
	return t
}
func (t PerformerEditsTable) AS(alias string) PerformerEditsTable { return newPerformerEdits(alias) }

var PerformerEdits = newPerformerEdits("")

type PerformerFavoritesTable struct {
	qb.Table
	AllColumns  qb.Expression
	PerformerID qb.Column[uuid.UUID]
	UserID      qb.Column[uuid.UUID]
	CreatedAt   qb.Column[time.Time]
}

func newPerformerFavorites(name string) PerformerFavoritesTable {
	t := PerformerFavoritesTable{Table: qb.NewTable("performer_favorites")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.AllColumns = qb.Columns(t.PerformerID, t.UserID, t.CreatedAt)
	return t
}
func (t PerformerFavoritesTable) AS(alias string) PerformerFavoritesTable {
	return newPerformerFavorites(alias)
}

var PerformerFavorites = newPerformerFavorites("")

type PerformerImagesTable struct {
	qb.Table
	AllColumns  qb.Expression
	PerformerID qb.Column[uuid.UUID]
	ImageID     qb.Column[uuid.UUID]
}

func newPerformerImages(name string) PerformerImagesTable {
	t := PerformerImagesTable{Table: qb.NewTable("performer_images")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.ImageID = qb.NewColumn[uuid.UUID](q, "image_id")
	t.AllColumns = qb.Columns(t.PerformerID, t.ImageID)
	return t
}
func (t PerformerImagesTable) AS(alias string) PerformerImagesTable { return newPerformerImages(alias) }

var PerformerImages = newPerformerImages("")

type PerformerPiercingsTable struct {
	qb.Table
	AllColumns  qb.Expression
	PerformerID qb.Column[uuid.UUID]
	Location    qb.Column[string]
	Description qb.Column[string]
}

func newPerformerPiercings(name string) PerformerPiercingsTable {
	t := PerformerPiercingsTable{Table: qb.NewTable("performer_piercings")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.Location = qb.NewColumn[string](q, "location")
	t.Description = qb.NewColumn[string](q, "description")
	t.AllColumns = qb.Columns(t.PerformerID, t.Location, t.Description)
	return t
}
func (t PerformerPiercingsTable) AS(alias string) PerformerPiercingsTable {
	return newPerformerPiercings(alias)
}

var PerformerPiercings = newPerformerPiercings("")

type PerformerPopularityAllTimeTable struct {
	qb.Table
	AllColumns  qb.Expression
	PerformerID qb.Column[uuid.UUID]
	UserCount   qb.Column[string]
}

func newPerformerPopularityAllTime(name string) PerformerPopularityAllTimeTable {
	t := PerformerPopularityAllTimeTable{Table: qb.NewTable("performer_popularity_all_time")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.UserCount = qb.NewColumn[string](q, "user_count")
	t.AllColumns = qb.Columns(t.PerformerID, t.UserCount)
	return t
}
func (t PerformerPopularityAllTimeTable) AS(alias string) PerformerPopularityAllTimeTable {
	return newPerformerPopularityAllTime(alias)
}

var PerformerPopularityAllTime = newPerformerPopularityAllTime("")

type PerformerRedirectsTable struct {
	qb.Table
	AllColumns qb.Expression
	SourceID   qb.Column[uuid.UUID]
	TargetID   qb.Column[uuid.UUID]
}

func newPerformerRedirects(name string) PerformerRedirectsTable {
	t := PerformerRedirectsTable{Table: qb.NewTable("performer_redirects")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SourceID = qb.NewColumn[uuid.UUID](q, "source_id")
	t.TargetID = qb.NewColumn[uuid.UUID](q, "target_id")
	t.AllColumns = qb.Columns(t.SourceID, t.TargetID)
	return t
}
func (t PerformerRedirectsTable) AS(alias string) PerformerRedirectsTable {
	return newPerformerRedirects(alias)
}

var PerformerRedirects = newPerformerRedirects("")

type PerformerSearchTable struct {
	qb.Table
	AllColumns     qb.Expression
	PerformerID    qb.Column[uuid.UUID]
	Name           qb.Column[string]
	Disambiguation qb.Column[string]
	Aliases        qb.Column[[]string]
	Gender         qb.Column[string]
}

func newPerformerSearch(name string) PerformerSearchTable {
	t := PerformerSearchTable{Table: qb.NewTable("performer_search")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.Name = qb.NewColumn[string](q, "name")
	t.Disambiguation = qb.NewColumn[string](q, "disambiguation")
	t.Aliases = qb.NewColumn[[]string](q, "aliases")
	t.Gender = qb.NewColumn[string](q, "gender")
	t.AllColumns = qb.Columns(t.PerformerID, t.Name, t.Disambiguation, t.Aliases, t.Gender)
	return t
}
func (t PerformerSearchTable) AS(alias string) PerformerSearchTable { return newPerformerSearch(alias) }

var PerformerSearch = newPerformerSearch("")

type PerformerTattoosTable struct {
	qb.Table
	AllColumns  qb.Expression
	PerformerID qb.Column[uuid.UUID]
	Location    qb.Column[string]
	Description qb.Column[string]
}

func newPerformerTattoos(name string) PerformerTattoosTable {
	t := PerformerTattoosTable{Table: qb.NewTable("performer_tattoos")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.Location = qb.NewColumn[string](q, "location")
	t.Description = qb.NewColumn[string](q, "description")
	t.AllColumns = qb.Columns(t.PerformerID, t.Location, t.Description)
	return t
}
func (t PerformerTattoosTable) AS(alias string) PerformerTattoosTable {
	return newPerformerTattoos(alias)
}

var PerformerTattoos = newPerformerTattoos("")

type PerformerUrlsTable struct {
	qb.Table
	AllColumns  qb.Expression
	PerformerID qb.Column[uuid.UUID]
	URL         qb.Column[string]
	SiteID      qb.Column[uuid.UUID]
}

func newPerformerUrls(name string) PerformerUrlsTable {
	t := PerformerUrlsTable{Table: qb.NewTable("performer_urls")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.URL = qb.NewColumn[string](q, "url")
	t.SiteID = qb.NewColumn[uuid.UUID](q, "site_id")
	t.AllColumns = qb.Columns(t.PerformerID, t.URL, t.SiteID)
	return t
}
func (t PerformerUrlsTable) AS(alias string) PerformerUrlsTable { return newPerformerUrls(alias) }

var PerformerUrls = newPerformerUrls("")

type PerformersTable struct {
	qb.Table
	AllColumns      qb.Expression
	ID              qb.Column[uuid.UUID]
	Name            qb.Column[string]
	Disambiguation  qb.Column[string]
	Gender          qb.Column[string]
	Ethnicity       qb.Column[string]
	Country         qb.Column[string]
	EyeColor        qb.Column[string]
	HairColor       qb.Column[string]
	Height          qb.Column[int]
	CupSize         qb.Column[string]
	BandSize        qb.Column[int]
	HipSize         qb.Column[int]
	WaistSize       qb.Column[int]
	BreastType      qb.Column[string]
	CareerStartYear qb.Column[int]
	CareerEndYear   qb.Column[int]
	CreatedAt       qb.Column[time.Time]
	UpdatedAt       qb.Column[time.Time]
	Deleted         qb.Column[bool]
	Birthdate       qb.Column[string]
	Deathdate       qb.Column[string]
}

func newPerformers(name string) PerformersTable {
	t := PerformersTable{Table: qb.NewTable("performers")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Name = qb.NewColumn[string](q, "name")
	t.Disambiguation = qb.NewColumn[string](q, "disambiguation")
	t.Gender = qb.NewColumn[string](q, "gender")
	t.Ethnicity = qb.NewColumn[string](q, "ethnicity")
	t.Country = qb.NewColumn[string](q, "country")
	t.EyeColor = qb.NewColumn[string](q, "eye_color")
	t.HairColor = qb.NewColumn[string](q, "hair_color")
	t.Height = qb.NewColumn[int](q, "height")
	t.CupSize = qb.NewColumn[string](q, "cup_size")
	t.BandSize = qb.NewColumn[int](q, "band_size")
	t.HipSize = qb.NewColumn[int](q, "hip_size")
	t.WaistSize = qb.NewColumn[int](q, "waist_size")
	t.BreastType = qb.NewColumn[string](q, "breast_type")
	t.CareerStartYear = qb.NewColumn[int](q, "career_start_year")
	t.CareerEndYear = qb.NewColumn[int](q, "career_end_year")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.Deleted = qb.NewColumn[bool](q, "deleted")
	t.Birthdate = qb.NewColumn[string](q, "birthdate")
	t.Deathdate = qb.NewColumn[string](q, "deathdate")
	t.AllColumns = qb.Columns(t.ID, t.Name, t.Disambiguation, t.Gender, t.Ethnicity, t.Country, t.EyeColor, t.HairColor, t.Height, t.CupSize, t.BandSize, t.HipSize, t.WaistSize, t.BreastType, t.CareerStartYear, t.CareerEndYear, t.CreatedAt, t.UpdatedAt, t.Deleted, t.Birthdate, t.Deathdate)
	return t
}
func (t PerformersTable) AS(alias string) PerformersTable { return newPerformers(alias) }

var Performers = newPerformers("")

type SceneEditsTable struct {
	qb.Table
	AllColumns qb.Expression
	EditID     qb.Column[uuid.UUID]
	SceneID    qb.Column[uuid.UUID]
}

func newSceneEdits(name string) SceneEditsTable {
	t := SceneEditsTable{Table: qb.NewTable("scene_edits")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.EditID = qb.NewColumn[uuid.UUID](q, "edit_id")
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.AllColumns = qb.Columns(t.EditID, t.SceneID)
	return t
}
func (t SceneEditsTable) AS(alias string) SceneEditsTable { return newSceneEdits(alias) }

var SceneEdits = newSceneEdits("")

type SceneFingerprintsTable struct {
	qb.Table
	AllColumns    qb.Expression
	FingerprintID qb.Column[int]
	SceneID       qb.Column[uuid.UUID]
	UserID        qb.Column[uuid.UUID]
	Duration      qb.Column[int]
	CreatedAt     qb.Column[time.Time]
	Vote          qb.Column[int]
}

func newSceneFingerprints(name string) SceneFingerprintsTable {
	t := SceneFingerprintsTable{Table: qb.NewTable("scene_fingerprints")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.FingerprintID = qb.NewColumn[int](q, "fingerprint_id")
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.Duration = qb.NewColumn[int](q, "duration")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.Vote = qb.NewColumn[int](q, "vote")
	t.AllColumns = qb.Columns(t.FingerprintID, t.SceneID, t.UserID, t.Duration, t.CreatedAt, t.Vote)
	return t
}
func (t SceneFingerprintsTable) AS(alias string) SceneFingerprintsTable {
	return newSceneFingerprints(alias)
}

var SceneFingerprints = newSceneFingerprints("")

type SceneImagesTable struct {
	qb.Table
	AllColumns qb.Expression
	SceneID    qb.Column[uuid.UUID]
	ImageID    qb.Column[uuid.UUID]
}

func newSceneImages(name string) SceneImagesTable {
	t := SceneImagesTable{Table: qb.NewTable("scene_images")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.ImageID = qb.NewColumn[uuid.UUID](q, "image_id")
	t.AllColumns = qb.Columns(t.SceneID, t.ImageID)
	return t
}
func (t SceneImagesTable) AS(alias string) SceneImagesTable { return newSceneImages(alias) }

var SceneImages = newSceneImages("")

type ScenePerformersTable struct {
	qb.Table
	AllColumns  qb.Expression
	SceneID     qb.Column[uuid.UUID]
	As          qb.Column[string]
	PerformerID qb.Column[uuid.UUID]
}

func newScenePerformers(name string) ScenePerformersTable {
	t := ScenePerformersTable{Table: qb.NewTable("scene_performers")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.As = qb.NewColumn[string](q, "as")
	t.PerformerID = qb.NewColumn[uuid.UUID](q, "performer_id")
	t.AllColumns = qb.Columns(t.SceneID, t.As, t.PerformerID)
	return t
}
func (t ScenePerformersTable) AS(alias string) ScenePerformersTable { return newScenePerformers(alias) }

var ScenePerformers = newScenePerformers("")

type ScenePopularityAllTimeTable struct {
	qb.Table
	AllColumns qb.Expression
	SceneID    qb.Column[uuid.UUID]
	UserCount  qb.Column[string]
}

func newScenePopularityAllTime(name string) ScenePopularityAllTimeTable {
	t := ScenePopularityAllTimeTable{Table: qb.NewTable("scene_popularity_all_time")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.UserCount = qb.NewColumn[string](q, "user_count")
	t.AllColumns = qb.Columns(t.SceneID, t.UserCount)
	return t
}
func (t ScenePopularityAllTimeTable) AS(alias string) ScenePopularityAllTimeTable {
	return newScenePopularityAllTime(alias)
}

var ScenePopularityAllTime = newScenePopularityAllTime("")

type ScenePopularityTrendingTable struct {
	qb.Table
	AllColumns    qb.Expression
	SceneID       qb.Column[uuid.UUID]
	TrendingCount qb.Column[string]
}

func newScenePopularityTrending(name string) ScenePopularityTrendingTable {
	t := ScenePopularityTrendingTable{Table: qb.NewTable("scene_popularity_trending")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.TrendingCount = qb.NewColumn[string](q, "trending_count")
	t.AllColumns = qb.Columns(t.SceneID, t.TrendingCount)
	return t
}
func (t ScenePopularityTrendingTable) AS(alias string) ScenePopularityTrendingTable {
	return newScenePopularityTrending(alias)
}

var ScenePopularityTrending = newScenePopularityTrending("")

type SceneRedirectsTable struct {
	qb.Table
	AllColumns qb.Expression
	SourceID   qb.Column[uuid.UUID]
	TargetID   qb.Column[uuid.UUID]
}

func newSceneRedirects(name string) SceneRedirectsTable {
	t := SceneRedirectsTable{Table: qb.NewTable("scene_redirects")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SourceID = qb.NewColumn[uuid.UUID](q, "source_id")
	t.TargetID = qb.NewColumn[uuid.UUID](q, "target_id")
	t.AllColumns = qb.Columns(t.SourceID, t.TargetID)
	return t
}
func (t SceneRedirectsTable) AS(alias string) SceneRedirectsTable { return newSceneRedirects(alias) }

var SceneRedirects = newSceneRedirects("")

type SceneSearchTable struct {
	qb.Table
	AllColumns     qb.Expression
	SceneID        qb.Column[uuid.UUID]
	SceneTitle     qb.Column[string]
	SceneDate      qb.Column[string]
	StudioName     qb.Column[string]
	NetworkName    qb.Column[string]
	StudioAliases  qb.Column[[]string]
	NetworkAliases qb.Column[[]string]
	PerformerNames qb.Column[[]string]
	SceneCode      qb.Column[string]
}

func newSceneSearch(name string) SceneSearchTable {
	t := SceneSearchTable{Table: qb.NewTable("scene_search")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.SceneTitle = qb.NewColumn[string](q, "scene_title")
	t.SceneDate = qb.NewColumn[string](q, "scene_date")
	t.StudioName = qb.NewColumn[string](q, "studio_name")
	t.NetworkName = qb.NewColumn[string](q, "network_name")
	t.StudioAliases = qb.NewColumn[[]string](q, "studio_aliases")
	t.NetworkAliases = qb.NewColumn[[]string](q, "network_aliases")
	t.PerformerNames = qb.NewColumn[[]string](q, "performer_names")
	t.SceneCode = qb.NewColumn[string](q, "scene_code")
	t.AllColumns = qb.Columns(t.SceneID, t.SceneTitle, t.SceneDate, t.StudioName, t.NetworkName, t.StudioAliases, t.NetworkAliases, t.PerformerNames, t.SceneCode)
	return t
}
func (t SceneSearchTable) AS(alias string) SceneSearchTable { return newSceneSearch(alias) }

var SceneSearch = newSceneSearch("")

type SceneTagsTable struct {
	qb.Table
	AllColumns qb.Expression
	SceneID    qb.Column[uuid.UUID]
	TagID      qb.Column[uuid.UUID]
}

func newSceneTags(name string) SceneTagsTable {
	t := SceneTagsTable{Table: qb.NewTable("scene_tags")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.TagID = qb.NewColumn[uuid.UUID](q, "tag_id")
	t.AllColumns = qb.Columns(t.SceneID, t.TagID)
	return t
}
func (t SceneTagsTable) AS(alias string) SceneTagsTable { return newSceneTags(alias) }

var SceneTags = newSceneTags("")

type SceneUrlsTable struct {
	qb.Table
	AllColumns qb.Expression
	SceneID    qb.Column[uuid.UUID]
	URL        qb.Column[string]
	SiteID     qb.Column[uuid.UUID]
}

func newSceneUrls(name string) SceneUrlsTable {
	t := SceneUrlsTable{Table: qb.NewTable("scene_urls")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SceneID = qb.NewColumn[uuid.UUID](q, "scene_id")
	t.URL = qb.NewColumn[string](q, "url")
	t.SiteID = qb.NewColumn[uuid.UUID](q, "site_id")
	t.AllColumns = qb.Columns(t.SceneID, t.URL, t.SiteID)
	return t
}
func (t SceneUrlsTable) AS(alias string) SceneUrlsTable { return newSceneUrls(alias) }

var SceneUrls = newSceneUrls("")

type ScenesTable struct {
	qb.Table
	AllColumns     qb.Expression
	ID             qb.Column[uuid.UUID]
	Title          qb.Column[string]
	Details        qb.Column[string]
	StudioID       qb.Column[uuid.UUID]
	CreatedAt      qb.Column[time.Time]
	UpdatedAt      qb.Column[time.Time]
	Duration       qb.Column[int]
	Director       qb.Column[string]
	Deleted        qb.Column[bool]
	Code           qb.Column[string]
	Date           qb.Column[string]
	ProductionDate qb.Column[string]
}

func newScenes(name string) ScenesTable {
	t := ScenesTable{Table: qb.NewTable("scenes")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Title = qb.NewColumn[string](q, "title")
	t.Details = qb.NewColumn[string](q, "details")
	t.StudioID = qb.NewColumn[uuid.UUID](q, "studio_id")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.Duration = qb.NewColumn[int](q, "duration")
	t.Director = qb.NewColumn[string](q, "director")
	t.Deleted = qb.NewColumn[bool](q, "deleted")
	t.Code = qb.NewColumn[string](q, "code")
	t.Date = qb.NewColumn[string](q, "date")
	t.ProductionDate = qb.NewColumn[string](q, "production_date")
	t.AllColumns = qb.Columns(t.ID, t.Title, t.Details, t.StudioID, t.CreatedAt, t.UpdatedAt, t.Duration, t.Director, t.Deleted, t.Code, t.Date, t.ProductionDate)
	return t
}
func (t ScenesTable) AS(alias string) ScenesTable { return newScenes(alias) }

var Scenes = newScenes("")

type SiteCategoriesTable struct {
	qb.Table
	AllColumns  qb.Expression
	ID          qb.Column[int]
	Name        qb.Column[string]
	Description qb.Column[string]
	SortOrder   qb.Column[int]
	CreatedAt   qb.Column[time.Time]
	UpdatedAt   qb.Column[time.Time]
}

func newSiteCategories(name string) SiteCategoriesTable {
	t := SiteCategoriesTable{Table: qb.NewTable("site_categories")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[int](q, "id")
	t.Name = qb.NewColumn[string](q, "name")
	t.Description = qb.NewColumn[string](q, "description")
	t.SortOrder = qb.NewColumn[int](q, "sort_order")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.AllColumns = qb.Columns(t.ID, t.Name, t.Description, t.SortOrder, t.CreatedAt, t.UpdatedAt)
	return t
}
func (t SiteCategoriesTable) AS(alias string) SiteCategoriesTable { return newSiteCategories(alias) }

var SiteCategories = newSiteCategories("")

type SitesTable struct {
	qb.Table
	AllColumns  qb.Expression
	ID          qb.Column[uuid.UUID]
	Name        qb.Column[string]
	Description qb.Column[string]
	URL         qb.Column[string]
	Regex       qb.Column[string]
	ValidTypes  qb.Column[[]string]
	CreatedAt   qb.Column[time.Time]
	UpdatedAt   qb.Column[time.Time]
	CategoryID  qb.Column[int]
	Highlighted qb.Column[bool]
}

func newSites(name string) SitesTable {
	t := SitesTable{Table: qb.NewTable("sites")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Name = qb.NewColumn[string](q, "name")
	t.Description = qb.NewColumn[string](q, "description")
	t.URL = qb.NewColumn[string](q, "url")
	t.Regex = qb.NewColumn[string](q, "regex")
	t.ValidTypes = qb.NewColumn[[]string](q, "valid_types")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.CategoryID = qb.NewColumn[int](q, "category_id")
	t.Highlighted = qb.NewColumn[bool](q, "highlighted")
	t.AllColumns = qb.Columns(t.ID, t.Name, t.Description, t.URL, t.Regex, t.ValidTypes, t.CreatedAt, t.UpdatedAt, t.CategoryID, t.Highlighted)
	return t
}
func (t SitesTable) AS(alias string) SitesTable { return newSites(alias) }

var Sites = newSites("")

type StudioAliasesTable struct {
	qb.Table
	AllColumns qb.Expression
	StudioID   qb.Column[uuid.UUID]
	Alias      qb.Column[string]
}

func newStudioAliases(name string) StudioAliasesTable {
	t := StudioAliasesTable{Table: qb.NewTable("studio_aliases")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.StudioID = qb.NewColumn[uuid.UUID](q, "studio_id")
	t.Alias = qb.NewColumn[string](q, "alias")
	t.AllColumns = qb.Columns(t.StudioID, t.Alias)
	return t
}
func (t StudioAliasesTable) AS(alias string) StudioAliasesTable { return newStudioAliases(alias) }

var StudioAliases = newStudioAliases("")

type StudioEditsTable struct {
	qb.Table
	AllColumns qb.Expression
	EditID     qb.Column[uuid.UUID]
	StudioID   qb.Column[uuid.UUID]
}

func newStudioEdits(name string) StudioEditsTable {
	t := StudioEditsTable{Table: qb.NewTable("studio_edits")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.EditID = qb.NewColumn[uuid.UUID](q, "edit_id")
	t.StudioID = qb.NewColumn[uuid.UUID](q, "studio_id")
	t.AllColumns = qb.Columns(t.EditID, t.StudioID)
	return t
}
func (t StudioEditsTable) AS(alias string) StudioEditsTable { return newStudioEdits(alias) }

var StudioEdits = newStudioEdits("")

type StudioFavoritesTable struct {
	qb.Table
	AllColumns qb.Expression
	StudioID   qb.Column[uuid.UUID]
	UserID     qb.Column[uuid.UUID]
	CreatedAt  qb.Column[time.Time]
}

func newStudioFavorites(name string) StudioFavoritesTable {
	t := StudioFavoritesTable{Table: qb.NewTable("studio_favorites")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.StudioID = qb.NewColumn[uuid.UUID](q, "studio_id")
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.AllColumns = qb.Columns(t.StudioID, t.UserID, t.CreatedAt)
	return t
}
func (t StudioFavoritesTable) AS(alias string) StudioFavoritesTable { return newStudioFavorites(alias) }

var StudioFavorites = newStudioFavorites("")

type StudioImagesTable struct {
	qb.Table
	AllColumns qb.Expression
	StudioID   qb.Column[uuid.UUID]
	ImageID    qb.Column[uuid.UUID]
}

func newStudioImages(name string) StudioImagesTable {
	t := StudioImagesTable{Table: qb.NewTable("studio_images")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.StudioID = qb.NewColumn[uuid.UUID](q, "studio_id")
	t.ImageID = qb.NewColumn[uuid.UUID](q, "image_id")
	t.AllColumns = qb.Columns(t.StudioID, t.ImageID)
	return t
}
func (t StudioImagesTable) AS(alias string) StudioImagesTable { return newStudioImages(alias) }

var StudioImages = newStudioImages("")

type StudioRedirectsTable struct {
	qb.Table
	AllColumns qb.Expression
	SourceID   qb.Column[uuid.UUID]
	TargetID   qb.Column[uuid.UUID]
}

func newStudioRedirects(name string) StudioRedirectsTable {
	t := StudioRedirectsTable{Table: qb.NewTable("studio_redirects")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SourceID = qb.NewColumn[uuid.UUID](q, "source_id")
	t.TargetID = qb.NewColumn[uuid.UUID](q, "target_id")
	t.AllColumns = qb.Columns(t.SourceID, t.TargetID)
	return t
}
func (t StudioRedirectsTable) AS(alias string) StudioRedirectsTable { return newStudioRedirects(alias) }

var StudioRedirects = newStudioRedirects("")

type StudioSearchTable struct {
	qb.Table
	AllColumns qb.Expression
	StudioID   qb.Column[uuid.UUID]
	Name       qb.Column[string]
	Network    qb.Column[string]
	Aliases    qb.Column[[]string]
}

func newStudioSearch(name string) StudioSearchTable {
	t := StudioSearchTable{Table: qb.NewTable("studio_search")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.StudioID = qb.NewColumn[uuid.UUID](q, "studio_id")
	t.Name = qb.NewColumn[string](q, "name")
	t.Network = qb.NewColumn[string](q, "network")
	t.Aliases = qb.NewColumn[[]string](q, "aliases")
	t.AllColumns = qb.Columns(t.StudioID, t.Name, t.Network, t.Aliases)
	return t
}
func (t StudioSearchTable) AS(alias string) StudioSearchTable { return newStudioSearch(alias) }

var StudioSearch = newStudioSearch("")

type StudioUrlsTable struct {
	qb.Table
	AllColumns qb.Expression
	StudioID   qb.Column[uuid.UUID]
	URL        qb.Column[string]
	SiteID     qb.Column[uuid.UUID]
}

func newStudioUrls(name string) StudioUrlsTable {
	t := StudioUrlsTable{Table: qb.NewTable("studio_urls")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.StudioID = qb.NewColumn[uuid.UUID](q, "studio_id")
	t.URL = qb.NewColumn[string](q, "url")
	t.SiteID = qb.NewColumn[uuid.UUID](q, "site_id")
	t.AllColumns = qb.Columns(t.StudioID, t.URL, t.SiteID)
	return t
}
func (t StudioUrlsTable) AS(alias string) StudioUrlsTable { return newStudioUrls(alias) }

var StudioUrls = newStudioUrls("")

type StudiosTable struct {
	qb.Table
	AllColumns     qb.Expression
	ID             qb.Column[uuid.UUID]
	Name           qb.Column[string]
	ParentStudioID qb.Column[uuid.UUID]
	CreatedAt      qb.Column[time.Time]
	UpdatedAt      qb.Column[time.Time]
	Deleted        qb.Column[bool]
}

func newStudios(name string) StudiosTable {
	t := StudiosTable{Table: qb.NewTable("studios")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Name = qb.NewColumn[string](q, "name")
	t.ParentStudioID = qb.NewColumn[uuid.UUID](q, "parent_studio_id")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.Deleted = qb.NewColumn[bool](q, "deleted")
	t.AllColumns = qb.Columns(t.ID, t.Name, t.ParentStudioID, t.CreatedAt, t.UpdatedAt, t.Deleted)
	return t
}
func (t StudiosTable) AS(alias string) StudiosTable { return newStudios(alias) }

var Studios = newStudios("")

type TagAliasesTable struct {
	qb.Table
	AllColumns qb.Expression
	TagID      qb.Column[uuid.UUID]
	Alias      qb.Column[string]
}

func newTagAliases(name string) TagAliasesTable {
	t := TagAliasesTable{Table: qb.NewTable("tag_aliases")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.TagID = qb.NewColumn[uuid.UUID](q, "tag_id")
	t.Alias = qb.NewColumn[string](q, "alias")
	t.AllColumns = qb.Columns(t.TagID, t.Alias)
	return t
}
func (t TagAliasesTable) AS(alias string) TagAliasesTable { return newTagAliases(alias) }

var TagAliases = newTagAliases("")

type TagCategoriesTable struct {
	qb.Table
	AllColumns  qb.Expression
	ID          qb.Column[uuid.UUID]
	Group       qb.Column[string]
	Name        qb.Column[string]
	Description qb.Column[string]
	CreatedAt   qb.Column[time.Time]
	UpdatedAt   qb.Column[time.Time]
}

func newTagCategories(name string) TagCategoriesTable {
	t := TagCategoriesTable{Table: qb.NewTable("tag_categories")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Group = qb.NewColumn[string](q, "group")
	t.Name = qb.NewColumn[string](q, "name")
	t.Description = qb.NewColumn[string](q, "description")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.AllColumns = qb.Columns(t.ID, t.Group, t.Name, t.Description, t.CreatedAt, t.UpdatedAt)
	return t
}
func (t TagCategoriesTable) AS(alias string) TagCategoriesTable { return newTagCategories(alias) }

var TagCategories = newTagCategories("")

type TagEditsTable struct {
	qb.Table
	AllColumns qb.Expression
	EditID     qb.Column[uuid.UUID]
	TagID      qb.Column[uuid.UUID]
}

func newTagEdits(name string) TagEditsTable {
	t := TagEditsTable{Table: qb.NewTable("tag_edits")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.EditID = qb.NewColumn[uuid.UUID](q, "edit_id")
	t.TagID = qb.NewColumn[uuid.UUID](q, "tag_id")
	t.AllColumns = qb.Columns(t.EditID, t.TagID)
	return t
}
func (t TagEditsTable) AS(alias string) TagEditsTable { return newTagEdits(alias) }

var TagEdits = newTagEdits("")

type TagRedirectsTable struct {
	qb.Table
	AllColumns qb.Expression
	SourceID   qb.Column[uuid.UUID]
	TargetID   qb.Column[uuid.UUID]
}

func newTagRedirects(name string) TagRedirectsTable {
	t := TagRedirectsTable{Table: qb.NewTable("tag_redirects")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.SourceID = qb.NewColumn[uuid.UUID](q, "source_id")
	t.TargetID = qb.NewColumn[uuid.UUID](q, "target_id")
	t.AllColumns = qb.Columns(t.SourceID, t.TargetID)
	return t
}
func (t TagRedirectsTable) AS(alias string) TagRedirectsTable { return newTagRedirects(alias) }

var TagRedirects = newTagRedirects("")

type TagSearchTable struct {
	qb.Table
	AllColumns qb.Expression
	TagID      qb.Column[uuid.UUID]
	Name       qb.Column[string]
	Aliases    qb.Column[[]string]
}

func newTagSearch(name string) TagSearchTable {
	t := TagSearchTable{Table: qb.NewTable("tag_search")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.TagID = qb.NewColumn[uuid.UUID](q, "tag_id")
	t.Name = qb.NewColumn[string](q, "name")
	t.Aliases = qb.NewColumn[[]string](q, "aliases")
	t.AllColumns = qb.Columns(t.TagID, t.Name, t.Aliases)
	return t
}
func (t TagSearchTable) AS(alias string) TagSearchTable { return newTagSearch(alias) }

var TagSearch = newTagSearch("")

type TagsTable struct {
	qb.Table
	AllColumns  qb.Expression
	ID          qb.Column[uuid.UUID]
	Name        qb.Column[string]
	Description qb.Column[string]
	CreatedAt   qb.Column[time.Time]
	UpdatedAt   qb.Column[time.Time]
	Deleted     qb.Column[bool]
	CategoryID  qb.Column[uuid.UUID]
}

func newTags(name string) TagsTable {
	t := TagsTable{Table: qb.NewTable("tags")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Name = qb.NewColumn[string](q, "name")
	t.Description = qb.NewColumn[string](q, "description")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.Deleted = qb.NewColumn[bool](q, "deleted")
	t.CategoryID = qb.NewColumn[uuid.UUID](q, "category_id")
	t.AllColumns = qb.Columns(t.ID, t.Name, t.Description, t.CreatedAt, t.UpdatedAt, t.Deleted, t.CategoryID)
	return t
}
func (t TagsTable) AS(alias string) TagsTable { return newTags(alias) }

var Tags = newTags("")

type UserNotificationsTable struct {
	qb.Table
	AllColumns qb.Expression
	UserID     qb.Column[uuid.UUID]
	Type       qb.Column[string]
}

func newUserNotifications(name string) UserNotificationsTable {
	t := UserNotificationsTable{Table: qb.NewTable("user_notifications")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.Type = qb.NewColumn[string](q, "type")
	t.AllColumns = qb.Columns(t.UserID, t.Type)
	return t
}
func (t UserNotificationsTable) AS(alias string) UserNotificationsTable {
	return newUserNotifications(alias)
}

var UserNotifications = newUserNotifications("")

type UserRolesTable struct {
	qb.Table
	AllColumns qb.Expression
	UserID     qb.Column[uuid.UUID]
	Role       qb.Column[string]
}

func newUserRoles(name string) UserRolesTable {
	t := UserRolesTable{Table: qb.NewTable("user_roles")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.UserID = qb.NewColumn[uuid.UUID](q, "user_id")
	t.Role = qb.NewColumn[string](q, "role")
	t.AllColumns = qb.Columns(t.UserID, t.Role)
	return t
}
func (t UserRolesTable) AS(alias string) UserRolesTable { return newUserRoles(alias) }

var UserRoles = newUserRoles("")

type UserTokensTable struct {
	qb.Table
	AllColumns qb.Expression
	ID         qb.Column[uuid.UUID]
	Data       qb.Column[string]
	Type       qb.Column[string]
	CreatedAt  qb.Column[time.Time]
	ExpiresAt  qb.Column[time.Time]
}

func newUserTokens(name string) UserTokensTable {
	t := UserTokensTable{Table: qb.NewTable("user_tokens")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Data = qb.NewColumn[string](q, "data")
	t.Type = qb.NewColumn[string](q, "type")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.ExpiresAt = qb.NewColumn[time.Time](q, "expires_at")
	t.AllColumns = qb.Columns(t.ID, t.Data, t.Type, t.CreatedAt, t.ExpiresAt)
	return t
}
func (t UserTokensTable) AS(alias string) UserTokensTable { return newUserTokens(alias) }

var UserTokens = newUserTokens("")

type UsersTable struct {
	qb.Table
	AllColumns   qb.Expression
	ID           qb.Column[uuid.UUID]
	Name         qb.Column[string]
	PasswordHash qb.Column[string]
	Email        qb.Column[string]
	APIKey       qb.Column[string]
	APICalls     qb.Column[int]
	LastAPICall  qb.Column[time.Time]
	CreatedAt    qb.Column[time.Time]
	UpdatedAt    qb.Column[time.Time]
	InvitedBy    qb.Column[uuid.UUID]
	InviteTokens qb.Column[int]
}

func newUsers(name string) UsersTable {
	t := UsersTable{Table: qb.NewTable("users")}
	t.Table.Alias = name
	q := t.Table.Qualifier()
	t.ID = qb.NewColumn[uuid.UUID](q, "id")
	t.Name = qb.NewColumn[string](q, "name")
	t.PasswordHash = qb.NewColumn[string](q, "password_hash")
	t.Email = qb.NewColumn[string](q, "email")
	t.APIKey = qb.NewColumn[string](q, "api_key")
	t.APICalls = qb.NewColumn[int](q, "api_calls")
	t.LastAPICall = qb.NewColumn[time.Time](q, "last_api_call")
	t.CreatedAt = qb.NewColumn[time.Time](q, "created_at")
	t.UpdatedAt = qb.NewColumn[time.Time](q, "updated_at")
	t.InvitedBy = qb.NewColumn[uuid.UUID](q, "invited_by")
	t.InviteTokens = qb.NewColumn[int](q, "invite_tokens")
	t.AllColumns = qb.Columns(t.ID, t.Name, t.PasswordHash, t.Email, t.APIKey, t.APICalls, t.LastAPICall, t.CreatedAt, t.UpdatedAt, t.InvitedBy, t.InviteTokens)
	return t
}
func (t UsersTable) AS(alias string) UsersTable { return newUsers(alias) }

var Users = newUsers("")
