// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credit_role.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const countCreditsForRole = `-- name: CountCreditsForRole :one
SELECT COUNT(*) FROM scene_credits WHERE credit_role_id = $1
`

func (q *Queries) CountCreditsForRole(ctx context.Context, creditRoleID int) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditsForRole, creditRoleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreditRole = `-- name: CreateCreditRole :one

INSERT INTO credit_roles (name, description, created_at, updated_at)
VALUES ($1, $2, now(), now())
RETURNING id, name, description, created_at, updated_at
`

type CreateCreditRoleParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

// Credit role queries
func (q *Queries) CreateCreditRole(ctx context.Context, arg CreateCreditRoleParams) (CreditRole, error) {
	row := q.db.QueryRow(ctx, createCreditRole, arg.Name, arg.Description)
	var i CreditRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditRoleTag = `-- name: CreateCreditRoleTag :exec
INSERT INTO credit_role_tags (credit_role_id, tag_id)
VALUES ($1, $2)
`

type CreateCreditRoleTagParams struct {
	CreditRoleID int       `db:"credit_role_id" json:"credit_role_id"`
	TagID        uuid.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) CreateCreditRoleTag(ctx context.Context, arg CreateCreditRoleTagParams) error {
	_, err := q.db.Exec(ctx, createCreditRoleTag, arg.CreditRoleID, arg.TagID)
	return err
}

const deleteAllCreditRoleTags = `-- name: DeleteAllCreditRoleTags :exec
DELETE FROM credit_role_tags
WHERE credit_role_id = $1
`

func (q *Queries) DeleteAllCreditRoleTags(ctx context.Context, creditRoleID int) error {
	_, err := q.db.Exec(ctx, deleteAllCreditRoleTags, creditRoleID)
	return err
}

const deleteCreditRole = `-- name: DeleteCreditRole :exec
DELETE FROM credit_roles WHERE id = $1
`

func (q *Queries) DeleteCreditRole(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteCreditRole, id)
	return err
}

const deleteCreditRoleTag = `-- name: DeleteCreditRoleTag :exec
DELETE FROM credit_role_tags
WHERE credit_role_id = $1 AND tag_id = $2
`

type DeleteCreditRoleTagParams struct {
	CreditRoleID int       `db:"credit_role_id" json:"credit_role_id"`
	TagID        uuid.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) DeleteCreditRoleTag(ctx context.Context, arg DeleteCreditRoleTagParams) error {
	_, err := q.db.Exec(ctx, deleteCreditRoleTag, arg.CreditRoleID, arg.TagID)
	return err
}

const findCreditRole = `-- name: FindCreditRole :one
SELECT id, name, description, created_at, updated_at FROM credit_roles WHERE id = $1
`

func (q *Queries) FindCreditRole(ctx context.Context, id int) (CreditRole, error) {
	row := q.db.QueryRow(ctx, findCreditRole, id)
	var i CreditRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCreditRoles = `-- name: GetAllCreditRoles :many
SELECT id, name, description, created_at, updated_at FROM credit_roles ORDER BY id ASC
`

func (q *Queries) GetAllCreditRoles(ctx context.Context) ([]CreditRole, error) {
	rows, err := q.db.Query(ctx, getAllCreditRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditRole{}
	for rows.Next() {
		var i CreditRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreditRolesByPerformer = `-- name: GetCreditRolesByPerformer :many
SELECT
    credit_roles.id, credit_roles.name, credit_roles.description, credit_roles.created_at, credit_roles.updated_at,
    COUNT(DISTINCT scenes.id) as scene_count
FROM credit_roles
JOIN scene_credits SC ON credit_roles.id = SC.credit_role_id
JOIN scenes ON SC.scene_id = scenes.id
WHERE SC.performer_id = $1 AND scenes.deleted = false
GROUP BY credit_roles.id
ORDER BY credit_roles.id ASC
`

type GetCreditRolesByPerformerRow struct {
	CreditRole CreditRole `db:"credit_role" json:"credit_role"`
	SceneCount int64      `db:"scene_count" json:"scene_count"`
}

func (q *Queries) GetCreditRolesByPerformer(ctx context.Context, performerID uuid.UUID) ([]GetCreditRolesByPerformerRow, error) {
	rows, err := q.db.Query(ctx, getCreditRolesByPerformer, performerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCreditRolesByPerformerRow{}
	for rows.Next() {
		var i GetCreditRolesByPerformerRow
		if err := rows.Scan(
			&i.CreditRole.ID,
			&i.CreditRole.Name,
			&i.CreditRole.Description,
			&i.CreditRole.CreatedAt,
			&i.CreditRole.UpdatedAt,
			&i.SceneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreditTagsByPerformer = `-- name: GetCreditTagsByPerformer :many
SELECT
    SC.credit_role_id,
    tags.id, tags.name, tags.description, tags.created_at, tags.updated_at, tags.deleted, tags.category_id,
    COUNT(DISTINCT scenes.id) as scene_count
FROM tags
JOIN scene_credit_tags SCT ON tags.id = SCT.tag_id
JOIN scene_credits SC ON SCT.scene_credit_id = SC.id
JOIN scenes ON SC.scene_id = scenes.id
WHERE SC.performer_id = $1 AND scenes.deleted = false
GROUP BY SC.credit_role_id, tags.id
ORDER BY SC.credit_role_id ASC, tags.name ASC
`

type GetCreditTagsByPerformerRow struct {
	CreditRoleID int   `db:"credit_role_id" json:"credit_role_id"`
	Tag          Tag   `db:"tag" json:"tag"`
	SceneCount   int64 `db:"scene_count" json:"scene_count"`
}

func (q *Queries) GetCreditTagsByPerformer(ctx context.Context, performerID uuid.UUID) ([]GetCreditTagsByPerformerRow, error) {
	rows, err := q.db.Query(ctx, getCreditTagsByPerformer, performerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCreditTagsByPerformerRow{}
	for rows.Next() {
		var i GetCreditTagsByPerformerRow
		if err := rows.Scan(
			&i.CreditRoleID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.Description,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
			&i.Tag.Deleted,
			&i.Tag.CategoryID,
			&i.SceneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForCreditRole = `-- name: GetTagsForCreditRole :many
SELECT t.id, t.name, t.description, t.created_at, t.updated_at, t.deleted, t.category_id
FROM credit_role_tags ctt
JOIN tags t ON ctt.tag_id = t.id
WHERE ctt.credit_role_id = $1
ORDER BY t.name ASC
`

type GetTagsForCreditRoleRow struct {
	Tag Tag `db:"tag" json:"tag"`
}

func (q *Queries) GetTagsForCreditRole(ctx context.Context, creditRoleID int) ([]GetTagsForCreditRoleRow, error) {
	rows, err := q.db.Query(ctx, getTagsForCreditRole, creditRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsForCreditRoleRow{}
	for rows.Next() {
		var i GetTagsForCreditRoleRow
		if err := rows.Scan(
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.Description,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
			&i.Tag.Deleted,
			&i.Tag.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditRole = `-- name: UpdateCreditRole :one
UPDATE credit_roles
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateCreditRoleParams struct {
	ID          int     `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) UpdateCreditRole(ctx context.Context, arg UpdateCreditRoleParams) (CreditRole, error) {
	row := q.db.QueryRow(ctx, updateCreditRole, arg.ID, arg.Name, arg.Description)
	var i CreditRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
