// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credit_attribute.sql

package queries

import (
	"context"
)

const countCreditsUsingAttribute = `-- name: CountCreditsUsingAttribute :one
SELECT COUNT(*) FROM scene_credit_attributes WHERE credit_attribute_id = $1
`

func (q *Queries) CountCreditsUsingAttribute(ctx context.Context, creditAttributeID int) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditsUsingAttribute, creditAttributeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreditAttribute = `-- name: CreateCreditAttribute :one

INSERT INTO credit_attributes (name, description, created_at, updated_at)
VALUES ($1, $2, now(), now())
RETURNING id, name, description, created_at, updated_at
`

type CreateCreditAttributeParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

// Credit attribute queries
func (q *Queries) CreateCreditAttribute(ctx context.Context, arg CreateCreditAttributeParams) (CreditAttribute, error) {
	row := q.db.QueryRow(ctx, createCreditAttribute, arg.Name, arg.Description)
	var i CreditAttribute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditAttributeType = `-- name: CreateCreditAttributeType :exec
INSERT INTO credit_attribute_types (credit_attribute_id, credit_type_id)
VALUES ($1, $2)
`

type CreateCreditAttributeTypeParams struct {
	CreditAttributeID int `db:"credit_attribute_id" json:"credit_attribute_id"`
	CreditTypeID      int `db:"credit_type_id" json:"credit_type_id"`
}

func (q *Queries) CreateCreditAttributeType(ctx context.Context, arg CreateCreditAttributeTypeParams) error {
	_, err := q.db.Exec(ctx, createCreditAttributeType, arg.CreditAttributeID, arg.CreditTypeID)
	return err
}

const deleteAllCreditAttributeTypes = `-- name: DeleteAllCreditAttributeTypes :exec
DELETE FROM credit_attribute_types WHERE credit_attribute_id = $1
`

func (q *Queries) DeleteAllCreditAttributeTypes(ctx context.Context, creditAttributeID int) error {
	_, err := q.db.Exec(ctx, deleteAllCreditAttributeTypes, creditAttributeID)
	return err
}

const deleteCreditAttribute = `-- name: DeleteCreditAttribute :exec
DELETE FROM credit_attributes WHERE id = $1
`

func (q *Queries) DeleteCreditAttribute(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteCreditAttribute, id)
	return err
}

const findCreditAttribute = `-- name: FindCreditAttribute :one
SELECT id, name, description, created_at, updated_at FROM credit_attributes WHERE id = $1
`

func (q *Queries) FindCreditAttribute(ctx context.Context, id int) (CreditAttribute, error) {
	row := q.db.QueryRow(ctx, findCreditAttribute, id)
	var i CreditAttribute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCreditAttributeTypes = `-- name: GetAllCreditAttributeTypes :many
SELECT credit_attribute_id, credit_type_id
FROM credit_attribute_types
ORDER BY credit_attribute_id, credit_type_id
`

func (q *Queries) GetAllCreditAttributeTypes(ctx context.Context) ([]CreditAttributeType, error) {
	rows, err := q.db.Query(ctx, getAllCreditAttributeTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditAttributeType{}
	for rows.Next() {
		var i CreditAttributeType
		if err := rows.Scan(&i.CreditAttributeID, &i.CreditTypeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCreditAttributes = `-- name: GetAllCreditAttributes :many
SELECT id, name, description, created_at, updated_at FROM credit_attributes ORDER BY name ASC
`

func (q *Queries) GetAllCreditAttributes(ctx context.Context) ([]CreditAttribute, error) {
	rows, err := q.db.Query(ctx, getAllCreditAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditAttribute{}
	for rows.Next() {
		var i CreditAttribute
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreditTypeIDsForAttribute = `-- name: GetCreditTypeIDsForAttribute :many
SELECT credit_type_id
FROM credit_attribute_types
WHERE credit_attribute_id = $1
ORDER BY credit_type_id ASC
`

func (q *Queries) GetCreditTypeIDsForAttribute(ctx context.Context, creditAttributeID int) ([]int, error) {
	rows, err := q.db.Query(ctx, getCreditTypeIDsForAttribute, creditAttributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var credit_type_id int
		if err := rows.Scan(&credit_type_id); err != nil {
			return nil, err
		}
		items = append(items, credit_type_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidAttributeIDsForType = `-- name: GetValidAttributeIDsForType :many
SELECT credit_attribute_id
FROM credit_attribute_types
WHERE credit_attribute_id = ANY($1::INT[])
  AND credit_type_id = $2
`

type GetValidAttributeIDsForTypeParams struct {
	AttributeIds []int `db:"attribute_ids" json:"attribute_ids"`
	CreditTypeID int   `db:"credit_type_id" json:"credit_type_id"`
}

// Of the given attribute ids, returns those applicable to the given credit type
func (q *Queries) GetValidAttributeIDsForType(ctx context.Context, arg GetValidAttributeIDsForTypeParams) ([]int, error) {
	rows, err := q.db.Query(ctx, getValidAttributeIDsForType, arg.AttributeIds, arg.CreditTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var credit_attribute_id int
		if err := rows.Scan(&credit_attribute_id); err != nil {
			return nil, err
		}
		items = append(items, credit_attribute_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditAttribute = `-- name: UpdateCreditAttribute :one
UPDATE credit_attributes
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateCreditAttributeParams struct {
	ID          int     `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) UpdateCreditAttribute(ctx context.Context, arg UpdateCreditAttributeParams) (CreditAttribute, error) {
	row := q.db.QueryRow(ctx, updateCreditAttribute, arg.ID, arg.Name, arg.Description)
	var i CreditAttribute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
