// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credit_type.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const countCreditsForType = `-- name: CountCreditsForType :one
SELECT COUNT(*) FROM scene_credits WHERE credit_type_id = $1
`

func (q *Queries) CountCreditsForType(ctx context.Context, creditTypeID int) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditsForType, creditTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreditType = `-- name: CreateCreditType :one

INSERT INTO credit_types (name, description, created_at, updated_at)
VALUES ($1, $2, now(), now())
RETURNING id, name, description, created_at, updated_at
`

type CreateCreditTypeParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

// Credit type queries
func (q *Queries) CreateCreditType(ctx context.Context, arg CreateCreditTypeParams) (CreditType, error) {
	row := q.db.QueryRow(ctx, createCreditType, arg.Name, arg.Description)
	var i CreditType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCreditType = `-- name: DeleteCreditType :exec
DELETE FROM credit_types WHERE id = $1
`

func (q *Queries) DeleteCreditType(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteCreditType, id)
	return err
}

const findCreditType = `-- name: FindCreditType :one
SELECT id, name, description, created_at, updated_at FROM credit_types WHERE id = $1
`

func (q *Queries) FindCreditType(ctx context.Context, id int) (CreditType, error) {
	row := q.db.QueryRow(ctx, findCreditType, id)
	var i CreditType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCreditTypes = `-- name: GetAllCreditTypes :many
SELECT id, name, description, created_at, updated_at FROM credit_types ORDER BY id ASC
`

func (q *Queries) GetAllCreditTypes(ctx context.Context) ([]CreditType, error) {
	rows, err := q.db.Query(ctx, getAllCreditTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditType{}
	for rows.Next() {
		var i CreditType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreditTypesByPerformer = `-- name: GetCreditTypesByPerformer :many
SELECT
    credit_types.id, credit_types.name, credit_types.description, credit_types.created_at, credit_types.updated_at,
    COUNT(DISTINCT scenes.id) as scene_count
FROM credit_types
JOIN scene_credits SC ON credit_types.id = SC.credit_type_id
JOIN scenes ON SC.scene_id = scenes.id
WHERE SC.performer_id = $1 AND scenes.deleted = false
GROUP BY credit_types.id
ORDER BY credit_types.id ASC
`

type GetCreditTypesByPerformerRow struct {
	CreditType CreditType `db:"credit_type" json:"credit_type"`
	SceneCount int64      `db:"scene_count" json:"scene_count"`
}

func (q *Queries) GetCreditTypesByPerformer(ctx context.Context, performerID uuid.UUID) ([]GetCreditTypesByPerformerRow, error) {
	rows, err := q.db.Query(ctx, getCreditTypesByPerformer, performerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCreditTypesByPerformerRow{}
	for rows.Next() {
		var i GetCreditTypesByPerformerRow
		if err := rows.Scan(
			&i.CreditType.ID,
			&i.CreditType.Name,
			&i.CreditType.Description,
			&i.CreditType.CreatedAt,
			&i.CreditType.UpdatedAt,
			&i.SceneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditType = `-- name: UpdateCreditType :one
UPDATE credit_types
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateCreditTypeParams struct {
	ID          int     `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) UpdateCreditType(ctx context.Context, arg UpdateCreditTypeParams) (CreditType, error) {
	row := q.db.QueryRow(ctx, updateCreditType, arg.ID, arg.Name, arg.Description)
	var i CreditType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
