// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scene_credit.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const createSceneCredit = `-- name: CreateSceneCredit :one

INSERT INTO scene_credits (scene_id, performer_id, credit_role_id, "as")
VALUES ($1, $2, $3, $4)
RETURNING id, scene_id, performer_id, credit_role_id, "as"
`

type CreateSceneCreditParams struct {
	SceneID      uuid.UUID `db:"scene_id" json:"scene_id"`
	PerformerID  uuid.UUID `db:"performer_id" json:"performer_id"`
	CreditRoleID int       `db:"credit_role_id" json:"credit_role_id"`
	As           *string   `db:"as" json:"as"`
}

// Scene credit queries
func (q *Queries) CreateSceneCredit(ctx context.Context, arg CreateSceneCreditParams) (SceneCredit, error) {
	row := q.db.QueryRow(ctx, createSceneCredit,
		arg.SceneID,
		arg.PerformerID,
		arg.CreditRoleID,
		arg.As,
	)
	var i SceneCredit
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.PerformerID,
		&i.CreditRoleID,
		&i.As,
	)
	return i, err
}

type CreateSceneCreditTagsParams struct {
	SceneCreditID int       `db:"scene_credit_id" json:"scene_credit_id"`
	TagID         uuid.UUID `db:"tag_id" json:"tag_id"`
}

type CreateSceneCreditsParams struct {
	SceneID      uuid.UUID `db:"scene_id" json:"scene_id"`
	PerformerID  uuid.UUID `db:"performer_id" json:"performer_id"`
	CreditRoleID int       `db:"credit_role_id" json:"credit_role_id"`
	As           *string   `db:"as" json:"as"`
}

const deleteSceneCreditTags = `-- name: DeleteSceneCreditTags :exec
DELETE FROM scene_credit_tags
WHERE scene_credit_id = $1
`

func (q *Queries) DeleteSceneCreditTags(ctx context.Context, sceneCreditID int) error {
	_, err := q.db.Exec(ctx, deleteSceneCreditTags, sceneCreditID)
	return err
}

const deleteSceneCredits = `-- name: DeleteSceneCredits :exec
DELETE FROM scene_credits WHERE scene_id = $1
`

func (q *Queries) DeleteSceneCredits(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSceneCredits, sceneID)
	return err
}

const findCreditTagsBySceneIds = `-- name: FindCreditTagsBySceneIds :many
SELECT sc.scene_id, sc.performer_id, sc.credit_role_id, t.id, t.name, t.description, t.created_at, t.updated_at, t.deleted, t.category_id
FROM scene_credit_tags sct
JOIN scene_credits sc ON sct.scene_credit_id = sc.id
JOIN tags t ON sct.tag_id = t.id
WHERE sc.scene_id = ANY($1::UUID[])
ORDER BY sc.scene_id, sc.performer_id, sc.credit_role_id, t.name
`

type FindCreditTagsBySceneIdsRow struct {
	SceneID      uuid.UUID `db:"scene_id" json:"scene_id"`
	PerformerID  uuid.UUID `db:"performer_id" json:"performer_id"`
	CreditRoleID int       `db:"credit_role_id" json:"credit_role_id"`
	Tag          Tag       `db:"tag" json:"tag"`
}

// Get all credit tags for multiple scenes (for DataLoader)
func (q *Queries) FindCreditTagsBySceneIds(ctx context.Context, sceneIds []uuid.UUID) ([]FindCreditTagsBySceneIdsRow, error) {
	rows, err := q.db.Query(ctx, findCreditTagsBySceneIds, sceneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindCreditTagsBySceneIdsRow{}
	for rows.Next() {
		var i FindCreditTagsBySceneIdsRow
		if err := rows.Scan(
			&i.SceneID,
			&i.PerformerID,
			&i.CreditRoleID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.Description,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
			&i.Tag.Deleted,
			&i.Tag.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSceneCreditsByIds = `-- name: FindSceneCreditsByIds :many
SELECT id, scene_id, performer_id, credit_role_id, "as"
FROM scene_credits
WHERE scene_id = ANY($1::UUID[])
ORDER BY scene_id
`

// Get credits for multiple scenes (for DataLoader)
func (q *Queries) FindSceneCreditsByIds(ctx context.Context, sceneIds []uuid.UUID) ([]SceneCredit, error) {
	rows, err := q.db.Query(ctx, findSceneCreditsByIds, sceneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneCredit{}
	for rows.Next() {
		var i SceneCredit
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.PerformerID,
			&i.CreditRoleID,
			&i.As,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSceneCredits = `-- name: GetSceneCredits :many
SELECT id, scene_id, performer_id, credit_role_id, "as" FROM scene_credits WHERE scene_id = $1
`

func (q *Queries) GetSceneCredits(ctx context.Context, sceneID uuid.UUID) ([]SceneCredit, error) {
	rows, err := q.db.Query(ctx, getSceneCredits, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneCredit{}
	for rows.Next() {
		var i SceneCredit
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.PerformerID,
			&i.CreditRoleID,
			&i.As,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSceneCreditsByRole = `-- name: GetSceneCreditsByRole :many
SELECT id, scene_id, performer_id, credit_role_id, "as" FROM scene_credits WHERE scene_id = $1 AND credit_role_id = $2
`

type GetSceneCreditsByRoleParams struct {
	SceneID      uuid.UUID `db:"scene_id" json:"scene_id"`
	CreditRoleID int       `db:"credit_role_id" json:"credit_role_id"`
}

// Get scene credits filtered by role
func (q *Queries) GetSceneCreditsByRole(ctx context.Context, arg GetSceneCreditsByRoleParams) ([]SceneCredit, error) {
	rows, err := q.db.Query(ctx, getSceneCreditsByRole, arg.SceneID, arg.CreditRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneCredit{}
	for rows.Next() {
		var i SceneCredit
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.PerformerID,
			&i.CreditRoleID,
			&i.As,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForCredit = `-- name: GetTagsForCredit :many
SELECT t.id, t.name, t.description, t.created_at, t.updated_at, t.deleted, t.category_id
FROM scene_credit_tags sct
JOIN tags t ON sct.tag_id = t.id
WHERE sct.scene_credit_id = $1
ORDER BY t.name ASC
`

type GetTagsForCreditRow struct {
	Tag Tag `db:"tag" json:"tag"`
}

func (q *Queries) GetTagsForCredit(ctx context.Context, sceneCreditID int) ([]GetTagsForCreditRow, error) {
	rows, err := q.db.Query(ctx, getTagsForCredit, sceneCreditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsForCreditRow{}
	for rows.Next() {
		var i GetTagsForCreditRow
		if err := rows.Scan(
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.Description,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
			&i.Tag.Deleted,
			&i.Tag.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
