// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scene_credit.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const createSceneCredit = `-- name: CreateSceneCredit :one

INSERT INTO scene_credits (scene_id, performer_id, credit_type_id, "as")
VALUES ($1, $2, $3, $4)
RETURNING id, scene_id, performer_id, credit_type_id, "as"
`

type CreateSceneCreditParams struct {
	SceneID      uuid.UUID `db:"scene_id" json:"scene_id"`
	PerformerID  uuid.UUID `db:"performer_id" json:"performer_id"`
	CreditTypeID int       `db:"credit_type_id" json:"credit_type_id"`
	As           *string   `db:"as" json:"as"`
}

// Scene credit queries
func (q *Queries) CreateSceneCredit(ctx context.Context, arg CreateSceneCreditParams) (SceneCredit, error) {
	row := q.db.QueryRow(ctx, createSceneCredit,
		arg.SceneID,
		arg.PerformerID,
		arg.CreditTypeID,
		arg.As,
	)
	var i SceneCredit
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.PerformerID,
		&i.CreditTypeID,
		&i.As,
	)
	return i, err
}

type CreateSceneCreditAttributesParams struct {
	SceneCreditID     int `db:"scene_credit_id" json:"scene_credit_id"`
	CreditAttributeID int `db:"credit_attribute_id" json:"credit_attribute_id"`
}

type CreateSceneCreditsParams struct {
	SceneID      uuid.UUID `db:"scene_id" json:"scene_id"`
	PerformerID  uuid.UUID `db:"performer_id" json:"performer_id"`
	CreditTypeID int       `db:"credit_type_id" json:"credit_type_id"`
	As           *string   `db:"as" json:"as"`
}

const deleteSceneCreditAttributes = `-- name: DeleteSceneCreditAttributes :exec
DELETE FROM scene_credit_attributes
WHERE scene_credit_id = $1
`

func (q *Queries) DeleteSceneCreditAttributes(ctx context.Context, sceneCreditID int) error {
	_, err := q.db.Exec(ctx, deleteSceneCreditAttributes, sceneCreditID)
	return err
}

const deleteSceneCredits = `-- name: DeleteSceneCredits :exec
DELETE FROM scene_credits WHERE scene_id = $1
`

func (q *Queries) DeleteSceneCredits(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSceneCredits, sceneID)
	return err
}

const findCreditAttributesBySceneCreditIds = `-- name: FindCreditAttributesBySceneCreditIds :many
SELECT sca.scene_credit_id, ca.id, ca.name, ca.description, ca.created_at, ca.updated_at
FROM scene_credit_attributes sca
JOIN credit_attributes ca ON sca.credit_attribute_id = ca.id
WHERE sca.scene_credit_id = ANY($1::INT[])
ORDER BY sca.scene_credit_id, ca.name
`

type FindCreditAttributesBySceneCreditIdsRow struct {
	SceneCreditID   int             `db:"scene_credit_id" json:"scene_credit_id"`
	CreditAttribute CreditAttribute `db:"credit_attribute" json:"credit_attribute"`
}

// Get attributes for multiple scene credits, keyed by scene_credit_id (for DataLoader)
func (q *Queries) FindCreditAttributesBySceneCreditIds(ctx context.Context, sceneCreditIds []int) ([]FindCreditAttributesBySceneCreditIdsRow, error) {
	rows, err := q.db.Query(ctx, findCreditAttributesBySceneCreditIds, sceneCreditIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindCreditAttributesBySceneCreditIdsRow{}
	for rows.Next() {
		var i FindCreditAttributesBySceneCreditIdsRow
		if err := rows.Scan(
			&i.SceneCreditID,
			&i.CreditAttribute.ID,
			&i.CreditAttribute.Name,
			&i.CreditAttribute.Description,
			&i.CreditAttribute.CreatedAt,
			&i.CreditAttribute.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSceneCreditsByIds = `-- name: FindSceneCreditsByIds :many
SELECT id, scene_id, performer_id, credit_type_id, "as"
FROM scene_credits
WHERE scene_id = ANY($1::UUID[])
ORDER BY scene_id
`

// Get credits for multiple scenes (for DataLoader)
func (q *Queries) FindSceneCreditsByIds(ctx context.Context, sceneIds []uuid.UUID) ([]SceneCredit, error) {
	rows, err := q.db.Query(ctx, findSceneCreditsByIds, sceneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneCredit{}
	for rows.Next() {
		var i SceneCredit
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.PerformerID,
			&i.CreditTypeID,
			&i.As,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSceneCredits = `-- name: GetSceneCredits :many
SELECT id, scene_id, performer_id, credit_type_id, "as" FROM scene_credits WHERE scene_id = $1
`

func (q *Queries) GetSceneCredits(ctx context.Context, sceneID uuid.UUID) ([]SceneCredit, error) {
	rows, err := q.db.Query(ctx, getSceneCredits, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneCredit{}
	for rows.Next() {
		var i SceneCredit
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.PerformerID,
			&i.CreditTypeID,
			&i.As,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSceneCreditsByType = `-- name: GetSceneCreditsByType :many
SELECT id, scene_id, performer_id, credit_type_id, "as" FROM scene_credits WHERE scene_id = $1 AND credit_type_id = $2
`

type GetSceneCreditsByTypeParams struct {
	SceneID      uuid.UUID `db:"scene_id" json:"scene_id"`
	CreditTypeID int       `db:"credit_type_id" json:"credit_type_id"`
}

// Get scene credits filtered by credit type
func (q *Queries) GetSceneCreditsByType(ctx context.Context, arg GetSceneCreditsByTypeParams) ([]SceneCredit, error) {
	rows, err := q.db.Query(ctx, getSceneCreditsByType, arg.SceneID, arg.CreditTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneCredit{}
	for rows.Next() {
		var i SceneCredit
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.PerformerID,
			&i.CreditTypeID,
			&i.As,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
